name: Continuous Integration

env:
  JOB_FAILS: "false"

on:
  pull_request:
    branches-ignore:
      - 'temp/*'

  push:
    branches-ignore:
      - 'temp/*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_compilation:
    name: Compilation check
    if: ${{ github.repository != vars.MIRROR_URL }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          set -e
          
          if [ -f Makefile ]; then
            echo "Detected Makefile"
            make -j$(nproc) 2>&1 | tee build.log
          
          elif [ -f CMakeLists.txt ]; then
            echo "Detected CMake project"
            cmake -B build
            cmake --build build -j$(nproc) 2>&1 | tee build.log
          
          else
            echo "No supported build system found"
            exit 1
          fi

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

  compilation_required:
    name: Compilation required
    if: ${{ github.repository != vars.MIRROR_URL }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          set -e
          
          if [ -f Makefile ]; then
            echo "Detected Makefile"
            make -j$(nproc) 2>&1
          
          elif [ -f CMakeLists.txt ]; then
            echo "Detected CMake project"
            cmake -B build
            cmake --build build -j$(nproc) 2>&1
          
          else
            echo "No supported build system found"
            exit 1
          fi

      - name: Check executables
        if: ${{ vars.EXECUTABLES != '' }}
        run: |
          for binary in ${{ vars.EXECUTABLES }}; do
            if [ ! -x "$binary" ]; then
              echo "::error::Missing executable: $binary"
              exit 1
            fi
          done


  check_coding_style:
    name: Coding style checking
    if: ${{ github.repository != vars.MIRROR_URL }}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    needs: check_compilation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check repository for unwanted files
        continue-on-error: true
        run: |
          banana-check-repo . 2>&1 | tee check.log
          if grep -qF "[Banana]" check.log; then
            echo "JOB_FAILS=true" >> $GITHUB_ENV
          fi

      - name: Annotations for useless files
        if: always()
        continue-on-error: true
        run: |
          if ! grep -qF "[Banana]" check.log; then
            echo "No coding style error found"
            exit 0
          fi

          # Extract unique files involved in Banana errors
          files=$(awk '/\[Banana\]/ {f=$1; sub(":", "", f); print f}' check.log | sort -u)
          
          echo "Files with errors:"
          echo "$files"
          
          # Check if ONLY ./libs/myteams/libmyteams.so is present
          if [ "$files" = "./libs/myteams/libmyteams.so" ]; then
            echo "Only libmyteams.so has errors → ignoring"
            echo "JOB_FAILS=false" >> $GITHUB_ENV
            exit 0
          fi
          
          echo "::group::Coding style errors"
          awk '
          /\[Banana\]/ {
          file = $1
          sub(":", "", file)

          level = "notice"
          if ($0 ~ /\[Fatal\]/) level="error"
          else if ($0 ~ /\[Major\]/) level="error"
          else if ($0 ~ /\[Minor\]/) level="warning"
          else if ($0 ~ /\[Info\]/) level="notice"
          
          msg = $0
          sub(/^[^:]+: \[Banana\] \[([^\]]+)\] /, "", msg)
          
            printf "::%s file=%s::%s\n", level, file, msg
          }
          ' check.log
          echo "::endgroup::"
          exit 84

      - name: Download build log
        uses: actions/download-artifact@v4
        with:
          name: build-log

      - name: Annotations for coding style errors
        if: always()
        run: |
          if ! grep -qF "[Banana]" build.log; then
            if [ "$JOB_FAILS" = "true" ]; then
              echo "::notice::unwanted files found in the repository"

              echo "JOB_FAILS=false" >> $GITHUB_ENV
              exit 42
            fi

            echo "No coding style error found"
            exit 0
          fi
          
          echo "::group::Coding style errors"
          awk '
          /\[Banana\]/ {

          split($1, loc, ":")
          file = loc[1]
          line = loc[2]

          level = "notice"
          if ($0 ~ /\[Fatal\]/) level="error"
          else if ($0 ~ /\[Major\]/) level="error"
          else if ($0 ~ /\[Minor\]/) level="warning"
          else if ($0 ~ /\[Info\]/) level="notice"

          msg = $0
          sub(/^[^:]*:[^:]*:[^:]*: [^:]*: /, "", msg)

            printf "::%s file=%s,line=%s,title=%s::%s\n", level, file, line, $NF, msg
          }
          ' build.log
          echo "::endgroup::"

          exit 84


  static_analysis:
    name: Static analysis with clang tidy
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: compilation_required
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy bear

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          if [ -f Makefile ]; then
            echo "Detected Makefile"
            make fclean
            bear -- make all -j
            python3 run-clang-tidy.py -j$(nproc) \
            -p . 2>&1 | tee analysis.log

          elif [ -f CMakeLists.txt ]; then
            echo "Detected CMake project"
            cmake -B build
            cmake --build build
            python3 run-clang-tidy.py -j$(nproc) \
            -p build 2>&1 | tee analysis.log
          fi

      - name: Annotations for clang tidy log
        if: always()
        continue-on-error: true
        run: |
          echo "::group::Static analysis errors"
          awk '
          /(warning:|error:)/ {

          split($1, loc, ":")
          file = loc[1]
          line = loc[2]

          level = "notice"
          if ($0 ~ /warning:/) level="warning"
          else if ($0 ~ /error:/) level="error"

          msg = $0
          sub(/^[^:]*:[^:]*:[^:]*: (warning:|error:) /, "", msg)
          sub(/^\[[^]]*\]/, "", msg)

            printf "::%s file=%s,line=%s,title=%s::%s\n", level, file, line, $NF, msg
          }
          ' analysis.log
          echo "::endgroup::"

          if grep "error:" analysis.log; then
            exit 84
          fi

          exit 0

  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
      statuses: write
    container: epitechcontent/epitest-docker
    needs: compilation_required
    steps:
      - name: Install dependencies
        run: |
          echo `clang --version`
          apt update
          apt install -y python3-full llvm-18 llvm-18-tools

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DWITH_COVERAGE=ON

      - name: Build binaries
        run: cmake --build build --target coverage --config Release -j$(nproc)

      - name: Run tests
        working-directory: build
        run: |
          ctest -V --output-junit test-results.xml || true

      - name: Fix Git ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Publish Test Results to GitHub Checks
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: GTest Results
          path: '**/test-results.xml'
          reporter: java-junit
          fail-on-error: false

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: build/coverage_html

  deploy-coverage:
    needs:
      - unit_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-html
          path: .

      - name: Debug coverage structure
        run: |
          tree 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

  push_to_mirror:
    needs:
      - check_coding_style
      - static_analysis
      - unit_test
    if: ${{ github.repository_owner == vars.USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - run: git fetch --unshallow
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.FULL_MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}